name: parensnet

channels:
  - conda-forge

dependencies:
  - python=3.12
  - pip
  #
  # C/C++ Module dependencies
  - openmpi-mpicc
  - gxx_linux-64
  - hdf5
  #
  # python libs from conda-forge
  - basedpyright
  - dask
  - devtools
  - h5py
  - jupyter
  - mpi4py
  - numpy
  - pandas
  - polars
  - psutil
  #- pybind11
  - pytest
  - pydantic
  - pyyaml
  - scikit-learn
  - scipy
  - tqdm
  - xlsxwriter
  #
  # pip dependencies
  - pip:
      - anndata
      - arboreto
      - lightgbm
      - scanpy
      - xgboost
      - git+https://github.com/srirampc/codetiming
