h5ad_file: "/localscratch/schockalingam6/tmp/pbmc20k.500/adata.20k.500.h5ad"
misi_data_file: "/localscratch/schockalingam6/tmp/pbmc20k.500/adata.20k.500.misidata.h5"
puc_file: "/localscratch/schockalingam6/tmp/pbmc20k.500/adata.20k.500.S6x4p.par_puc.h5"
pidc_file: "/localscratch/schockalingam6/tmp/pbmc20k.500/adata.20k.500.SQ6x4px30.par_pidc.h5"
#
nrounds: 6
nsamples: 20
nobs: 0
nvars: 0
mode:
  #- "samples_ranges"
  - "puc2pidc"
quantile_filter: 0.3
save_nodes: False
save_node_pairs: True
