h5ad_file: "/localscratch/schockalingam6/tmp/pbmc20k.500//adata_leiden.20k.500.h5ad"
misi_data_file: "/localscratch/schockalingam6/tmp/pbmc20k.500/adata.20k.500.SCunion.misidata.h5"
puc_file: "/localscratch/schockalingam6/tmp/pbmc20k.500/adata.20k.500.SCunion6x4p_puc.h5"
pidc_file: "/localscratch/schockalingam6/tmp/pbmc20k.500/adata.20k.500.SCunion6x4p_pidc.h5"
nrounds: 6
nsamples: 200
nobs: 0
nvars: 0
wflow_dir: "/localscratch/schockalingam6/tmp/pbmc20k.500/Sunion6x4p"
#mode: "samples_ranges"
mode:
  - "cluster_union"
save_nodes: False
save_node_pairs: True
