h5ad_file: "/localscratch/schockalingam6/tmp/pbmc20k.5k//adata.20k.5k.h5ad"
misi_data_file: "/localscratch/schockalingam6/tmp/pbmc20k.5k//adata.20k.5k.misidata.h5"
puc_file: "/localscratch/schockalingam6/tmp/pbmc20k.5k//adata.20k.5k.S6x4p_puc.h5"
pidc_file: "/localscratch/schockalingam6/tmp/pbmc20k.5k//adata.20k.5k.SQ6x4px30_pidc.h5"
nrounds: 6
nsamples: 200
nobs: 0
nvars: 0
#mode: "samples_ranges"
mode:
  - "puc2pidc"
quantile_filter: 0.3
save_nodes: False
save_node_pairs: True
